# Generated by Django 5.2.8 on 2026-02-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0010_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(default='https://github.com/ethanMinson?tab=repositories', max_length=500),
        ),
    ]
